### ISSUE TITLE
Add Support for Postgresql

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/Blog#207]
Add Postgresql support (for example via Entity Framework).

**Comment by diegodrf** [comment]
Hi @linkdotnet, I would like to help you. 
I don't have experience acting in open-source projects, but I would like to start.

Could you give me details about the issue? It's just to add the support for Postgresql or did you try before and find incompatibilities?

**Comment by linkdotnet** [comment]
Hey @diegodrf - cool, help is always appreciated.

I did not try until now with PostgreSQL, but as the blog isn't using anything exotic, I don't expect much trouble here.

There are multiple ways to solve the issue. The easiest way is to use [Entity Framework Provider](https://www.npgsql.org/efcore/). There you already have a repository and all the code around. See [Infrastructure](https://github.com/linkdotnet/Blog/tree/master/src/LinkDotNet.Blog.Infrastructure).

So adding the package will almost do everything for you.  You just have to add the new provider in [PersistenceProvider](https://github.com/linkdotnet/Blog/blob/master/src/LinkDotNet.Blog.Infrastructure/Persistence/PersistenceProvider.cs) and create a new PostgreSQL extension in the [RegistrationExtensions](https://github.com/linkdotnet/Blog/tree/master/src/LinkDotNet.Blog.Web/RegistrationExtensions) namespace.

The more complicated way is not to use Entity Framework and use something else. For this you would have to implement your own [IRepository](https://github.com/linkdotnet/Blog/blob/master/src/LinkDotNet.Blog.Infrastructure/Persistence/IRepository.cs). You could have a look at how the `SqlRepository` does it at the moment, but that is up to you.

The general workflow looks like this:
1. In the appsettings.json you can define your storage provider - the string has to be the same as in the PersistenceProvider class
2. On Startup the blog checks for this and calls the [StorageProviderExtensions](https://github.com/linkdotnet/Blog/blob/master/src/LinkDotNet.Blog.Web/RegistrationExtensions/StorageProviderExtensions.cs), which you would add the new PostgreSQL type, and registers all the necessary types.
3. The components just get injected the `IRepository<T>` so they don't know what underlying technology is used.

If you need more details let me know. You can also just start, open a PR and ask your questions if this is easier for you

**Comment by EliasMasche** [comment]
Hello there, Is this issue still open today I discovered this project

**Comment by linkdotnet** [comment]
There were some attempts but this is currently open and up for grabs if you like to tackle it.

**Comment by EliasMasche** [comment]
Thanks for the reply, I will take a look during the weekend and my free time and use the earlier comment details you wrote.

**Comment by linkdotnet** [comment]
Thanks - if you have any question, just start shooting ;)

**Comment by EliasMasche** [comment]
question, for support of postgresql do I aim with net 9.0 or any specific version?

**Comment by linkdotnet** [comment]
`net9.0` and EF 9. I merged a PR enabling EF 9 just some seconds ago.

**Comment by EliasMasche** [comment]
Thanks will update my devenv with both and do a fork of the repo and another question do I keep using this issue thread about Postgre or I go with new one?

**Comment by linkdotnet** [comment]
> Thanks will update my devenv with both and do a fork of the repo and another question do I keep using this issue thread about Postgre or I go with new one?

I would keep them here if they are related. Maybe it helps others as well.

**Comment by EliasMasche** [comment]
Hello, on my [fork ](https://github.com/linkdotnet/Blog/compare/master...EliasMasche:Blog:master) I was able to include support for PostgreSQL, I have this error when trying to save a blog into the DB

it comes from `public async ValueTask StoreAsync(TEntity entity)` inside `Repository.cs`

<details>
  Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=An error occurred while saving the entity changes. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__50.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.<SaveChangesAsync>d__8.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__111.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__115.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__63.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__63.MoveNext()
   at LinkDotNet.Blog.Infrastructure.Persistence.Sql.Repository`1.<StoreAsync>d__7.MoveNext() in F:\Dev\CSharp\Blog\src\LinkDotNet.Blog.Infrastructure\Persistence\Sql\Repository.cs:line 93
   at LinkDotNet.Blog.Infrastructure.Persistence.Sql.Repository`1.<StoreAsync>d__7.MoveNext() in F:\Dev\CSharp\Blog\src\LinkDotNet.Blog.Infrastructure\Persistence\Sql\Repository.cs:line 93
   at LinkDotNet.Blog.Infrastructure.Persistence.CachedRepository`1.<StoreAsync>d__7.MoveNext() in F:\Dev\CSharp\Blog\src\LinkDotNet.Blog.Infrastructure\Persistence\CachedRepository.cs:line 52
   at LinkDotNet.Blog.Web.Features.Admin.BlogPostEditor.CreateBlogPost.<StoreBlogPostAsync>d__1.MoveNext() in F:\Dev\CSharp\Blog\src\LinkDotNet.Blog.Web\Features\Admin\BlogPostEditor\CreateBlogPost.razor:line 14
   at Microsoft.AspNetCore.Components.ComponentBase.<CallStateHasChangedOnAsyncCompletion>d__30.MoveNext()

This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array, range, or multirange. (Parameter 'value')
<summary>Error Exception</summary>

</details>

The error happens because Npgsql changed his behavior of mapping Date and time creating a breaking change:
[https://www.npgsql.org/doc/types/datetime.html](https://www.npgsql.org/doc/types/datetime.html)

So it requires to use this line of code to use the legacy behavior

> AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

Or to update with the new mapping or use their NodaTime Plugin:

[https://www.npgsql.org/doc/types/nodatime.html?tabs=datasource](https://www.npgsql.org/doc/types/nodatime.html?tabs=datasource)

**Comment by linkdotnet** [comment]
Hey @EliasMasche,

Thanks for the update. Hmm I see the problem. Well, there are two ways of solving this.

1. `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);`: Probably best suited in the `StorageProviderExtensions.AddStorageProvider` when you add the Postgres Stuff.
2. Saving our dates as UTC. That might be anyway the best option. Currently, everything is local (server) time. That isn't really good to be honest! When dates are saved, we could either use `DateTimeOffset` and do a migration or just define UTC as kind for `DateTime`.

I do think the latter one, is the way to go.

**Comment by EliasMasche** [comment]
Another issue that can and will show up with local (server) time is that in my case, I have different servers(on-premise and cloud) in different timezones, so if I migrate or restore a backup, it will provoke issues with different times.

How it will work using migration with `DateTimeOffset`? I don't have experience using these two but I am for defining UTC as kind for `DateTime`

**Comment by linkdotnet** [comment]
> How it will work using migration with DateTimeOffset? I don't have experience using these two but I am for defining UTC as kind for DateTime

Basically the `UpdatedDate` and `ScheduledPublishDate` will become `DateTimeOffset` with all their usages.
This has to be also reflected in the data model (EF Configuration).

But for now - saving everything as UTC is the best option (both of these values). Maybe some adoptions in the background services have to be made as well and how this information is presented to the user. But I can take over that part.

**Comment by EliasMasche** [comment]
So I create a PR with the initial support of PostgreSQL and from there you continue with the necessary changes?

**Comment by linkdotnet** [comment]
> So I create a PR with the initial support of PostgreSQL and from there you continue with the necessary changes?

Indeed. The changes will be small, so that is absolutely fine.

**Comment by EliasMasche** [comment]
Created the PR

**Comment by linkdotnet** [comment]
Done by @EliasMasche in #399
