### ISSUE TITLE
EF Core + MySQL Empty JSON Stack Traces

### ISSUE THREAD

**Issue by ncosentino** [linkdotnet/Blog#376]
Disclaimer: This might have been because I migrated posts manually, but I am not entirely sure. They seem to render completely fine in the UI from what I can see, but I am getting application exceptions flooding Azure:

`
An exception occurred while iterating over the results of a query for context type 'LinkDotNet.Blog.Infrastructure.Persistence.Sql.BlogDbContext'.
MySqlConnector.MySqlException (0x80004005): Invalid JSON text in argument 1 to function json_table: "The document is empty." at position 0.
at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
at MySqlConnector.Core.ResultSet.ScanRowAsync(IOBehavior ioBehavior, Row row, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ResultSet.cs:line 244
at MySqlConnector.Core.ResultSet.ReadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ResultSet.cs:line 207
at MySqlConnector.MySqlDataReader.ReadAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 38
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable 1.AsyncEnumerator.MoveNextAsync()
`

As you can see, it's spamming pretty good:
<img width="407" alt="image" src="https://github.com/user-attachments/assets/f02aa7eb-8da0-47f7-92e3-8e3e1a3f0a1d">

I am not exactly sure what to check here -- but I think tags *might* be the only thing that is JSON-esque in the database columns for a blog post? I could be wrong. I cannot access my MySQL instance from this machine, but I can try to query directly and see if I find any obvious records.

Posting this simply for visibility in case it pops up anywhere else for anyone. But I may be able to close it out if I find I made an invalid record manually.

**Comment by ncosentino** [comment]
I have gone through all database records and ensured a ShortDescription is set and all Tags are set to at least have something like
`["Programming"]`

I'm still getting the error. For reference, I am trying to access this route:
`https://devleader.ca/searchByTag/ROM`
(This showed up in my cloudflare analytics so I was curious)

If I access something like this:
`https://devleader.ca/searchByTag/programming`

It all works as expected (no exception, and records load in the UI)

**Comment by linkdotnet** [comment]
Hey Nick,

I am pretty sure that has nothing to do with the approach of manually converting your blog posts. I suspect more MySQL or the MySQL driver for Entity Framework. I tested all the implementation details against MariaDB, which seems to have much better support for that (at least the more I dig into the topic). So I have to check what is the way forward (and don't use MariaDB for my tests :D)

PS: Also `https://devleader.ca/searchByTag/programming` will fail eventually if you wait.

**Comment by linkdotnet** [comment]
That makes the issue even more interesting. I try to find some time the upcoming days.

**Comment by linkdotnet** [comment]
There should be a new EF 9 Version of the `Pomelo` LINQ Driver. I hope that fixes things.

**Comment by linkdotnet** [comment]
<img width="799" alt="image" src="https://github.com/user-attachments/assets/a80c1e12-faa4-432a-8327-64c1f0e7791f">

I am battling a different kind of beast here :D

**Comment by linkdotnet** [comment]
I don't have a solution, nor do I have a clue what is the problem. But something about the term: **Dev Leader Weekly** throws of the JSON Support in MySQL. Using tags like "C#" or ".NET" do work fine, but as soon as I throw in **Dev Leader Weekly** into the mix,
a) I get the exception you are receiving
b) If I use the generated code from EF and just executed manually against the MySQL database, it retrieves post that don't even have the tag in them.

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/2a7cae43-0646-4331-a602-598c80521957">

**Comment by linkdotnet** [comment]
Probably caused by: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1933

**Comment by linkdotnet** [comment]
I moved to another MYSQL Provider. if the issue pops up again, we can reopen the ticket. For now, I assume it is "done".
